import { CategoryInfo } from "./types";

export const CATEGORIES: Record<string, CategoryInfo> = {
  laboral: {
    id: "laboral",
    title: "Direito do Trabalho",
    description: "Conflitos entre trabalhadores e entidades empregadoras, despedimentos, indemnizações, salários em atraso e direitos da LGT.",
    icon: "Briefcase",
    laws: "Lei Geral do Trabalho de Angola (Lei n.º 12/23, de 29 de Agosto)",
    questions: [
      {
        id: "nome",
        label: "Nome Completo do Trabalhador",
        type: "text",
        placeholder: "Ex: Manuel Baptista",
        required: true,
      },
      {
        id: "tem_contrato",
        label: "Existe contrato de trabalho celebrado por escrito?",
        type: "select",
        options: [
          "Sim, contrato escrito por tempo indeterminado",
          "Sim, contrato escrito a termo (com prazo)",
          "Não, apenas acordo verbal (sem documento)",
          "Não sei ou não tenho a certeza",
        ],
        required: true,
      },
      {
        id: "antiguidade",
        label: "Há quanto tempo trabalhava ou trabalha nesta empresa?",
        type: "select",
        options: [
          "Menos de 6 meses",
          "Entre 6 meses e 1 ano",
          "Entre 1 e 5 anos",
          "Mais de 5 anos",
        ],
        required: true,
      },
      {
        id: "salario",
        label: "Qual é o seu salário bruto mensal aproximado (em Kwanzas - AOA)?",
        type: "number",
        placeholder: "Ex: 150000",
        required: true,
      },
      {
        id: "problema_principal",
        label: "Qual é a situação principal que motivou esta consulta?",
        type: "select",
        options: [
          "Despedimento verbal ou sem justa causa",
          "Salários ou subsídios em atraso (Férias, Natal)",
          "Aplicação de processo disciplinar ou suspensão",
          "Falta de condições de segurança ou acidente de trabalho",
          "Assédio laboral ou alteração unilateral de horário/função",
          "Falta de canalização de contribuições para o INSS",
          "Outro problema contratual",
        ],
        required: true,
      },
      {
        id: "descricao",
        label: "Descreva com detalhe as circunstâncias do ocorrido (datas, atitudes, testemunhas):",
        type: "textarea",
        placeholder: "Por favor, explique o que aconteceu de forma cronológica. Dica: Se mencionar valores específicos, como o seu salário bruto mensal, anos de serviço ou dias de atraso de pagamento, o sistema de Calculadoras Jurídicas calculará automaticamente as indemnizações e proporcionais no seu diagnóstico final!",
        required: true,
      },
    ],
  },
  familia: {
    id: "familia",
    title: "Direito de Família e Sucessões",
    description: "Casamento, união de facto (alambamento), divórcios, partilha de bens, pensão de alimentos, poder paternal e partilha de heranças.",
    icon: "Heart",
    laws: "Código de Família de Angola (Decreto-Lei n.º 1/88) e o disposto no Código Civil para Sucessões",
    questions: [
      {
        id: "nome",
        label: "Seu Nome Completo",
        type: "text",
        placeholder: "Ex: Paula Van-Dúnem",
        required: true,
      },
      {
        id: "tipo_relacao",
        label: "Qual o regime ou natureza da vossa relação ou união?",
        type: "select",
        options: [
          "Casamento Civil (Comunhão de Bens)",
          "União de Facto reconhecida (ou por reconhecer judicialmente)",
          "Casamento Tradicional (Alambamento / noivado) sem registo civil",
          "Casamento Religioso apenas",
          "Sem relação de casal direta (apenas laço parental ou herdeiro)",
        ],
        required: true,
      },
      {
        id: "filhos",
        label: "Existem filhos menores de idade gerados desta relação?",
        type: "select",
        options: [
          "Não civilmente menor de idade",
          "Sim, 1 filho menor",
          "Sim, 2 ou mais filhos menores",
        ],
        required: true,
      },
      {
        id: "problema_principal",
        label: "Qual o assunto principal do seu conflito ou dúvida familiar?",
        type: "select",
        options: [
          "Processo de divórcio e partilha de bens comuns",
          "Pensões de alimentos para filhos menores (incumprimento)",
          "Regulação do poder paternal ou guarda dos filhos",
          "Reconhecimento judicial de União de Facto pós-morte ou rutura",
          "Herança e partilha de bens deixados por pessoa falecida",
          "Violência doméstica ou medidas de proteção urgente",
          "Outro assunto de família",
        ],
        required: true,
      },
      {
        id: "descricao",
        label: "Esclareça os factos familiares que geraram o problema de forma detalhada:",
        type: "textarea",
        placeholder: "Indique datas importantes, comportamento da outra parte, etc. Dica: Se for um caso de pensão de alimentos, mencione o rendimento mensal líquido do provedor e o número de filhos menores; o sistema utilizará as calculadoras de família para estimar o valor e o intervalo judicial esperado no seu relatório preliminar!",
        required: true,
      },
    ],
  },
  imobiliario: {
    id: "imobiliario",
    title: "Arrendamento e Imobiliário",
    description: "Contratos de arrendamento residencial ou comercial, ameaça de despejo ilegal, obras, pagamento de rendas e compra e venda de lotes.",
    icon: "Home",
    laws: "Código Civil Angolano, Lei de Terras de Angola e Lei do Arrendamento Urbano",
    questions: [
      {
        id: "nome",
        label: "Seu Nome Completo",
        type: "text",
        placeholder: "Ex: António Luvualo",
        required: true,
      },
      {
        id: "posicao",
        label: "Qual é a sua qualidade no âmbito deste contrato ou imóvel?",
        type: "select",
        options: [
          "Inquilino (Arrendatário)",
          "Senhorio (Proprietário)",
          "Promitente Comprador de Terreno / Casa",
          "Promitente Vendedor / Cedente",
          "Outro",
        ],
        required: true,
      },
      {
        id: "contrato_escrito",
        label: "Existe um contrato assinado por escrito pelas partes?",
        type: "select",
        options: [
          "Sim, contrato por escrito com reconhecimento de assinaturas no Cartório Notarial",
          "Sim, contrato escrito simples (sem reconhecimento)",
          "Não, contrato meramente verbal (apenas acordos informais)",
          "Não, mas possuo recibos de pagamento de renda / sinal",
        ],
        required: true,
      },
      {
        id: "valor_mensal",
        label: "Qual é o valor financeiro aproximado do negócio ou renda mensal (em Kwanzas)?",
        type: "number",
        placeholder: "Ex: 200000",
        required: true,
      },
      {
        id: "problema_principal",
        label: "Qual é o litígio ou conflito central deste caso?",
        type: "select",
        options: [
          "Ameaça ou notificação de despejo ilegal por parte do senhorio",
          "Atraso ou incumprimento reiterado no pagamento das rendas",
          "Falta de obras urgentes ou manutenção estrutural do imóvel",
          "Senhorio recusa a devolução da caução paga inicialmente",
          "Disputa de título de posse, demarcação de terrenos ou invasão",
          "Incumprimento ou atraso na entrega de imóvel comprado sobre planta",
          "Outro litígio de natureza civil",
        ],
        required: true,
      },
      {
        id: "descricao",
        label: "Explique minuciosamente o litígio imobiliário ou contratual:",
        type: "textarea",
        placeholder: "Descreva quando iniciou o contrato, se existem notificações escritas, qual o comportamento da contraparte e a sua principal dúvida. Dica: Se existirem rendas em atraso ou valores caucionais retidos, mencione os montantes para o sistema efectuar o cálculo automático de juros e multas!",
        required: true,
      },
    ],
  },
  consumidor: {
    id: "consumidor",
    title: "Direito do Consumidor",
    description: "Defesa dos seus direitos perante empresas, compra de bens com defeito, recusa de garantia, engano em faturas e serviços abusivos.",
    icon: "ShieldAlert",
    laws: "Lei de Defesa do Consumidor de Angola (Lei n.º 15/03, de 22 de Julho)",
    questions: [
      {
        id: "nome",
        label: "Seu Nome Completo",
        type: "text",
        placeholder: "Ex: Domingas Neto",
        required: true,
      },
      {
        id: "produto_ou_servico",
        label: "Qual foi o produto ou serviço adquirido?",
        type: "text",
        placeholder: "Ex: Aparelho de Ar Condicionado / Internet de Fibra",
        required: true,
      },
      {
        id: "empresa",
        label: "Qual é o nome da empresa fornecedora ou vendedora?",
        type: "text",
        placeholder: "Ex: Empresa de Telecomunicações X / Loja de Eletrodomésticos Y",
        required: true,
      },
      {
        id: "reclamação",
        label: "Efetuou uma queixa ou reclamação formal à referida empresa?",
        type: "select",
        options: [
          "Sim, registei no Livro de Reclamações físico ou digital",
          "Sim, enviei carta com aviso de receção / e-mail formal",
          "Sim, mas apenas verbalmente (telefone ou balcão de atendimento)",
          "Não, ainda não apresentei qualquer reclamação",
        ],
        required: true,
      },
      {
        id: "problema_principal",
        label: "Indique a infração principal que a empresa cometeu:",
        type: "select",
        options: [
          "Produto apresenta defeito / avaria e recusam devolver o dinheiro ou reparar",
          "Serviço contratado não funciona (falha contínua) mas continuam a cobrar",
          "Cobrança ilegal de pacotes adicionais ou faturas de valor abusivo",
          "Publicidade enganosa ou informações falsas no momento da compra",
          "Recusa de cancelamento de plano de fidelização contratual",
          "Dano causado ao utilizador por má utilização de técnica ou imperícia",
          "Outro desrespeito aos direitos do consumidor",
        ],
        required: true,
      },
      {
        id: "descricao",
        label: "Descreva a sua experiência e o motivo pelo qual se sente lesado(a):",
        type: "textarea",
        placeholder: "Detalhe o valor cobrado, o tempo que durou o transtorno, se tem faturas ou provas e o que diz a resposta da empresa. Dica: Se houver um valor financeiro em disputa, indique-o explicitamente para que o sistema estime o potencial reembolso ou indemnização base com adicionais de mora!",
        required: true,
      },
    ],
  },
  geral: {
    id: "geral",
    title: "Casos Gerais e Outros Conflitos",
    description: "Partilhe outra situação jurídica que não se enquadre nas categorias anteriores, como vizinhos, trânsito, dívidas e administração pública.",
    icon: "Scale",
    laws: "Código Civil Angolano, Código de Processo Civil e Legislação Correlativa de Angola",
    questions: [
      {
        id: "nome",
        label: "Seu Nome Completo",
        type: "text",
        placeholder: "Ex: Mateus dos Santos",
        required: true,
      },
      {
        id: "subcategoria",
        label: "Qual destes âmbitos melhor enquadra a sua questão?",
        type: "select",
        options: [
          "Conflitos e danos entre vizinhos (barulho, infiltrações, marcos)",
          "Acidente de viação / colisão e recusa de pagamento de danos ou seguros",
          "Dívidas contraídas de teor pessoal ou empréstimos não pagos",
          "Contestações contra decisões da Administração Pública ou Direção de Impostos",
          "Danificação de propriedade, herança contestada complexa ou registos em cartório",
          "Outro assunto de caráter cível ou geral",
        ],
        required: true,
      },
      {
        id: "contraparte",
        label: "Quem é o sujeito com quem tem o conflito?",
        type: "select",
        options: [
          "Um vizinho ou indivíduo particular",
          "Uma repartição pública / Estado Angolano / Direção Municipal",
          "Um familiar ou ex-parceiro comercial",
          "Uma instituição bancária, seguradora ou empresa privada",
          "Outra entidade",
        ],
        required: true,
      },
      {
        id: "descricao",
        label: "Faça uma síntese pormenorizada do caso e da sua dúvida jurídica:",
        type: "textarea",
        placeholder: "Procure fornecer todas as informações possíveis. Dica: Se o conflito envolve uma dívida, um empréstimo ou danos materiais, descreva o valor em causa e as datas de incumprimento; o sistema aplicará as fórmulas legais para emitir um cálculo orientador dos juros e compensação acumulados!",
        required: true,
      },
    ],
  },
};
